name: Wiki Sync

on:
  push:
    branches:
    - master
    paths:
    - 'pages/**'

jobs:
  sync:

    name: Synchronize Wiki
    runs-on: ubuntu-latest
    if: github.repository == 'Slimefun/Wiki'

    steps:
    - name: Checking out repository
      uses: actions/checkout@v4

    - name: Setting up node.js
      uses: actions/setup-node@v4
      with:
        node-version: '10.x'

    - name: Scanning for dead links
      run: node src/missing.js
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Syncing to github-wiki
      run: sh src/sync.sh
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
